<<<<<<< HEAD
CREATE DATABASE Restoran
GO
USE Restoran;
GO
CREATE TABLE Kategoriler
(Kategori_ID INT PRIMARY KEY IDENTITY(1,1),
Kategori_Adi NVARCHAR(50)
);

CREATE TABLE Yemekler
(Yemek_ID INT PRIMARY KEY IDENTITY(1,1),
Kategori_ID INT FOREIGN KEY REFERENCES Kategoriler(Kategori_ID),
Yemek_Adi NVARCHAR(50),
Fiyat DECIMAL(10,2)
);

CREATE TABLE Masalar
(Masa_ID INT PRIMARY KEY IDENTITY(1,1),
Masa_No INT,
Kapasite INT
);

CREATE TABLE Personel
(Personel_ID INT PRIMARY KEY IDENTITY(1,1),
Ad NVARCHAR(50),
Soyad NVARCHAR(50),
Gorev NVARCHAR(50)
);

CREATE TABLE Siparisler
(Siparis_ID INT PRIMARY KEY IDENTITY(1,1),
Masa_ID INT FOREIGN KEY REFERENCES Masalar(Masa_ID),
Personel_ID INT FOREIGN KEY REFERENCES Personel(Personel_ID),
Siparis_Tarihi DATETIME DEFAULT GETDATE()
);

CREATE TABLE Siparis_Detay
(Detay_ID INT PRIMARY KEY IDENTITY(1,1),
Siparis_ID INT FOREIGN KEY REFERENCES Siparisler(Siparis_ID),
Yemek_ID INT FOREIGN KEY REFERENCES Yemekler(Yemek_ID),
Adet INT
=======
CREATE DATABASE Restoran
GO
USE Restoran;
GO
CREATE TABLE Kategoriler
(Kategori_ID INT PRIMARY KEY IDENTITY(1,1),
Kategori_Adi NVARCHAR(50)
);

CREATE TABLE Yemekler
(Yemek_ID INT PRIMARY KEY IDENTITY(1,1),
Kategori_ID INT FOREIGN KEY REFERENCES Kategoriler(Kategori_ID),
Yemek_Adi NVARCHAR(50),
Fiyat DECIMAL(10,2)
);

CREATE TABLE Masalar
(Masa_ID INT PRIMARY KEY IDENTITY(1,1),
Masa_No INT,
Kapasite INT
);

CREATE TABLE Personel
(Personel_ID INT PRIMARY KEY IDENTITY(1,1),
Ad NVARCHAR(50),
Soyad NVARCHAR(50),
Gorev NVARCHAR(50)
);

CREATE TABLE Siparisler
(Siparis_ID INT PRIMARY KEY IDENTITY(1,1),
Masa_ID INT FOREIGN KEY REFERENCES Masalar(Masa_ID),
Personel_ID INT FOREIGN KEY REFERENCES Personel(Personel_ID),
Siparis_Tarihi DATETIME DEFAULT GETDATE()
);

CREATE TABLE Siparis_Detay
(Detay_ID INT PRIMARY KEY IDENTITY(1,1),
Siparis_ID INT FOREIGN KEY REFERENCES Siparisler(Siparis_ID),
Yemek_ID INT FOREIGN KEY REFERENCES Yemekler(Yemek_ID),
Adet INT
>>>>>>> 7807bcae97c88fdfbbbaf4a4683d0cbfc817b039
);